apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: openloyalty
data:
  config.js: |-
    const config = {
        "apiUrl": "http://api.example.com/api",
        "dateFormat": "YYYY-MM-DD",
        "dateTimeFormat": "YYYY-MM-DD HH:mm",
        "perPage": 20,
        "debug": false,
        "modules": []
    };
    window.OpenLoyaltyConfig = config;
  .env.prod: |
    APP_ENV=prod
    APP_SECRET=__REPLACE_IT__
    RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    DATABASE_URL=pgsql://openloyalty:openloyalty@db:5432/openloyalty
    DATABASE_VERSION='9.6'
    MAILER_URL=smtp://mail:1025
    GELF_SERVER=logstash
    GELF_PORT=12201
    ELK_HOST=elk:9200
    VARNISH_HOST=varnish
    VARNISH_CACHE_BASE_URL=localhost
    VARNISH_TTL=30
    VARNISH_INVALIDATION=true
    VARNISH_DEBUG=false
    REDIS_HOST=redisserver
    REDIS_PORT=6379

    api_url=http://openloyalty.localhost/api
    admin_url=http://openloyalty.localhost:8182/
    customer_url=http://openloyalty.localhost:8183/
    merchant_url=http://openloyalty.localhost:8184/
    reset_password_url=\#!/password/reset
    frontend_activate_account_url=\#!/customer/panel/customer/registration/activate
    frontend_invitation_url=\#!/register/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php
  namespace: openloyalty
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 80
    pm.start_servers = 15
    pm.min_spare_servers = 15
    pm.max_spare_servers = 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish
  namespace: openloyalty
data:
  settings.vcl: |
    import directors;

    backend default_server {
      .host = "api";
      .port = "80";
      .max_connections = 300;

      .first_byte_timeout     = 300s;
      .connect_timeout        = 5s;
      .between_bytes_timeout  = 2s;
    }

    acl purge {
      # ACL we'll use later to allow purges
      "localhost";
      "127.0.0.1";
      "::1";
      "php";
      "api";
    }

    sub vcl_init {
      new vdir = directors.round_robin();
      vdir.add_backend(default_server);
    }
---
